export const projects = [
  {
    title: 'GTFO',
    description: "Inspired by AF Talent Management, I developed a mock talent agency with both model showcasing and model shopping services website using Hostinger's Web Hosting service and builder.",
      image: '/images/gtfo.png',
      tags: [],
    source: null,
    visit: 'https://gtfo-m6lwqwpzxptbrvzm.builder-preview.com/',
    id: 12,
  },
  {
    title: 'Mookie',
    description: "I developed a mock cookie delivery website using Hostinger's Web Hosting service and builder.",
      image: '/images/mookie.png',
      tags: [],
    source: null,
    visit: 'https://mookie-a0xwoopkr1cpe6r3.builder-preview.com/',
    id: 11,
  },
  {
    title: 'Ableton',
    description: "Using NextJs and TailwindCSS, I helped develop ableton.com.",
      image: '/images/ableton.png',
      tags: [ 'HTML', 'TailwindCSS', 'NextJs'],
    source: null,
    visit: 'https://www.ableton.com/en/',
    id: 10,
  },
  {
    title: 'Anges Vu Research Portfolio',
    description: "Using NextJs and TailwindCSS, I helped develop a research portfolio for a friend working on her PhD in Linguistics.",
      image: '/images/anges.png',
      tags: [ 'HTML', 'TailwindCSS', 'NextJs'],
    source: "https://github.com/genepaolo/angesvu",
    visit: 'https://angesvu.vercel.app/',
    id: 9,
  },
  {
    title: 'CordialMD',
    description: "Using React and Node.js, I created a simple healthcare provider website. This was a project for a client in Healthcare.",
      image: '/images/cordial.png',
      tags: [ 'HTML', 'CSS', 'JS/React'],
    source: "https://github.com/genepaolo/angesvu",
    visit: "https://cordialhp.com/",
    id: 8,
  },
  {
    title: 'Weaverry',
    description: "Using React, I created a single page website for Weaverry.",
      image: '/images/weaverry.png',
      tags: [ 'HTML', 'CSS', 'JS/React'],
    source: null,
    visit: 'https://www.weaverry.com/',
    id: 7,
  },
  {
    title: 'Gene Tech',
    description: "Using NextJs and TailwindCSS, I developed a blog website to discuss LeetCode Guides and World Development in the Tech Space.",
      image: '/images/gene-tech.png',
      tags: [ 'HTML', 'TailwindCSS', 'JS/React', 'NextJs'],
    source: "https://github.com/genepaolo/gene-tech",
    visit: 'https://gene-tech.vercel.app/',
    id: 6,
  },
  {
    title: 'Bordial Next Generations',
    description: "Using React, Node.js, Express & MongoDB I created a Full Stack MERN Application. BNG is a replica of a website that I created for a client in Healthcare.",
      image: '/images/bordial-next-gen.png',
      tags: [ 'HTML', 'CSS', 'JS/React', 'NodeJs/Express', 'MongoDB'],
    source: null,
    visit: 'https://bordial-next-generations.herokuapp.com/',
    id: 5,
  },
  {
    title: 'Sorting Visualizer',
    description:"This is a visualizer that demonstrates/animates different sorting algorithms (Bubble Sort, Insertion Sort, Selection Sort, Quick Sort, & Merge Sort). This is created using React and Redux to better understand the JS library.",
    image: '/images/sorting-visual.png',
    tags: [ 'HTML', 'CSS/SASS', 'JS/React', 'Redux'],
    source: 'https://github.com/genepaolo/sorting-visualizer',
    visit: 'https://genepaolo.github.io/sorting-visualizer/',
    id: 4,
  },
  {
    title: 'Travel Touring Project',
    description: "This is a markup of a fake travel touring project for the purpose of learning and practicing UI techniques with HTML and CSS/SASS.",
      image: '/images/travel-touring.png',
      tags: [ 'HTML', 'CSS/SASS'],
    source: 'https://github.com/genepaolo/traveling-touring-project/',
    visit: 'https://genepaolo.github.io/traveling-touring-project/',
    id: 3,
  },
  {
    title: 'Gene Reel',
    description: "This was a fairly simple frontend application using HTML, CSS, SASS, and JavaScript with the React library. I was inspired by the Netflix Scrolling UI and wanted to animate fetched movie data using the TMDb API.",
    image: '/images/gene-reel.png',
    tags: [ 'HTML', 'CSS/SASS', 'JS/React'],
    source: 'https://github.com/genepaolo/gene-reel',
    visit: 'https://genepaolo.github.io/gene-reel/#/',
    id: 2,
  },
  {
    title: 'Todolist',
    description: "Using Node.js, EJS, Express & MongoDB I created a short todolist project. This is my first time using EJS so I wanted to learn by incorporating it with a backend.",
      image: '/images/todo-list.png',
      tags: [ 'HTML', 'CSS', 'EJS', 'NodeJs/Express', 'MongoDB'],
    source: null,
    visit: null,
    id: 1,
  },
  {
    title: 'No JS Interactive Resume',
    description:"This is a small project using only HTML, CSS, and SASS without Bootstrap or Javascript. I never truly appreciated Javascript until you need to find workaround when you cannot select the parent node.",
    image: '/images/no-js-resume.png',
    tags: [ 'HTML', 'CSS/SASS'],
    source: 'https://github.com/genepaolo/resume-gene',
    visit: 'https://genepaolo.github.io/resume-gene/',
    id: 0,
  }
];
