export const projects = [
  {
    title: 'Bordial Next Generations',
    description: "Using React, Node.js, Express & MongoDB I created a Full Stack MERN Application. BNG is a replica of a website that I created for Cordial Healthcare Providers. Due to some compnay conflicts, the website was taken down but I still wished to showcase the webiste!",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://bordial-next-generations.herokuapp.com/',
    visit: null,
    id: 0,
  },
  {
    title: 'No JS Interactive Resume',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://genepaolo.github.io/resume-gene/',
    visit: 'https://github.com/genepaolo/resume-gene',
    id: 1,
  },
  {
    title: 'WebRTC App',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/3.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];
