export const projects = [
  {
    title: 'Bordial Next Generations',
    description: "Using React, Node.js, Express & MongoDB I created a Full Stack MERN Application. BNG is a replica of a website that I created for Cordial Healthcare Providers. Due to some compnay conflicts, the website was taken down but I still wished to showcase the webiste!",
      image: '/images/1.png',
      tags: [ 'HTML', 'CSS', 'JS/React', 'NodeJs/Express', 'MongoDB'],
    source: null,
    visit: 'https://bordial-next-generations.herokuapp.com/',
    id: 0,
  },
  {
    title: 'Sorting Visualizer',
    description:"This is a visualizer that demonstrates/animates different sorting algorithms (Bubble Sort, Insertion Sort, Selection Sort, Quick Sort, & Merge Sort). This is created using React and Redux to better understand the JS library.",
    image: '/images/2.png',
    tags: [ 'HTML', 'CSS/SASS', 'JS/React', 'Redux'],
    source: 'https://github.com/genepaolo/sorting-visualizer',
    visit: 'https://genepaolo.github.io/sorting-visualizer/',
    id: 1,
  },
  {
    title: 'Travel Touring Project',
    description: "This is a markup of a fake travel touring project for the purpose of learning and practicing UI techniques with HTML and CSS/SASS.",
      image: '/images/3.png',
      tags: [ 'HTML', 'CSS/SASS'],
    source: 'https://github.com/genepaolo/traveling-touring-project/',
    visit: 'https://genepaolo.github.io/traveling-touring-project/',
    id: 2,
  },
  {
    title: 'Gene Reel',
    description: "This was a fairly simple frontend application using HTML, CSS, SASS, and JavaScript with the React library. I was inspired by the Netflix Scrolling UI and wanted to animate fetched movie data using the TMDb API.",
    image: '/images/4.png',
    tags: [ 'HTML', 'CSS/SASS', 'JS/React'],
    source: 'https://github.com/genepaolo/gene-reel',
    visit: 'https://genepaolo.github.io/gene-reel/#/',
    id: 3,
  },
  {
    title: 'Todolist',
    description: "Using Node.js, EJS, Express & MongoDB I created a short todolist project. This is my first time using EJS so I wanted to learn by incorporating it with a backend.",
      image: '/images/5.png',
      tags: [ 'HTML', 'CSS', 'EJS', 'NodeJs/Express', 'MongoDB'],
    source: null,
    visit: 'https://gene-todolist.herokuapp.com/',
    id: 4,
  },
  {
    title: 'No JS Interactive Resume',
    description:"This is a small project using only HTML, CSS, and SASS without Bootstrap or Javascript. I never truly appreciated Javascript until you need to find workaround when you cannot select the parent node.",
    image: '/images/6.png',
    tags: [ 'HTML', 'CSS/SASS'],
    source: 'https://github.com/genepaolo/resume-gene',
    visit: 'https://genepaolo.github.io/resume-gene/',
    id: 5,
  }
];
